name: logfmt
version: 0.4.2
author: Jonathan Clem <jonathan@jclem.net>
description: A set of tools for working with logfmt-style log lines.
homepage: https://github.com/jclem/logfmt-dart
dev_dependencies:
  mock: '>=0.11.0+2 <0.12.0'
  path: '>=1.3.0 <2.0.0'
  unittest: '>=0.11.0+5 <0.12.0'
